/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tectuinno.seriallab.view;

import com.tectuinno.seriallab.application.WorkSpaceFileStorer;
import com.tectuinno.seriallab.core.ConsoleDisplayMode;
import com.tectuinno.seriallab.core.FlowControlMode;
import com.tectuinno.seriallab.core.FramingMode;
import com.tectuinno.seriallab.core.ParityMode;
import com.tectuinno.seriallab.core.TxEndingMode;
import com.tectuinno.seriallab.core.WorkSpaceProperties;
import com.tectuinno.seriallab.view.shared.work_space.GeneralWorkspaceDataParameters;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author root
 */
public class FrWorkSpaceWizard extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrWorkSpaceWizard.class.getName());
    private WorkSpaceProperties initialWorkSpaceProperties;
    private GeneralWorkspaceDataParameters generalWorkspaceDataParameters;
    private boolean accepted;
    
    /**
     * Creates new form FrWorkSpaceWizard
     */
    public FrWorkSpaceWizard(JFrame parent,WorkSpaceProperties initialWorkSpaceProperties) {
        super(parent,"Nuevo espacio de trabajo",true);
        this.initialWorkSpaceProperties = initialWorkSpaceProperties;
        this.accepted = false;
        this.generalWorkspaceDataParameters = new GeneralWorkspaceDataParameters();
        initComponents();        
        this.addGeneralWorkSpaceDataParameters();
        this.configParityModeCombobox();
        this.configureStopbitsSpinnerModel();
        this.configFlowControlModeCombobox();
        this.configureTxEndingmodeComboBox();
        this.configureFramingModeComboBox();
        this.configureConsoleDisplayModeComboBox();
        this.setCurrentDateOnWorkApaceCreation();
        this.setLocationRelativeTo(parent);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configTimeStampButonGroup = new javax.swing.ButtonGroup();
        panelPrincipalContainer = new javax.swing.JPanel();
        tabbPaneParametersFields = new javax.swing.JTabbedPane();
        panelWorkSpaceGeneralSettings = new javax.swing.JPanel();
        panelUartSettings = new javax.swing.JPanel();
        panelGeneralUartWorkSpaceParameters = new javax.swing.JPanel();
        lblDataBits = new javax.swing.JLabel();
        spinnerBaudRate = new javax.swing.JSpinner();
        lblDefaultBaudRate = new javax.swing.JLabel();
        spinnerDataBits = new javax.swing.JSpinner();
        lblUartParity = new javax.swing.JLabel();
        comboBoxParityMode = new javax.swing.JComboBox<>();
        lblStopBits = new javax.swing.JLabel();
        spinnerStopBits = new javax.swing.JSpinner();
        comboBoxFlowControlModel = new javax.swing.JComboBox<>();
        lblFlowControll1 = new javax.swing.JLabel();
        panelConsoleAndSendParameters = new javax.swing.JPanel();
        lblEndingMode = new javax.swing.JLabel();
        comboBoxTxEndingMode = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        radioButtonDisableTimeStamp = new javax.swing.JRadioButton();
        radioButtonEnableTimeStamp = new javax.swing.JRadioButton();
        lblDisplayMode = new javax.swing.JLabel();
        comboBoxConsoleDisplayMode = new javax.swing.JComboBox<>();
        panelFramingModeParameters = new javax.swing.JPanel();
        lblFramingMode = new javax.swing.JLabel();
        comboBoxFramingmode = new javax.swing.JComboBox<>();
        buttonCreateWorkspace = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nuevo espacio de trabajo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onClosingDialog(evt);
            }
        });

        panelWorkSpaceGeneralSettings.setLayout(new java.awt.BorderLayout());
        tabbPaneParametersFields.addTab("General", panelWorkSpaceGeneralSettings);

        panelGeneralUartWorkSpaceParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros UART"));

        lblDataBits.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblDataBits.setText("Data bits:");

        spinnerBaudRate.setModel(new javax.swing.SpinnerNumberModel(9600, 1200, 260000, 5));
        spinnerBaudRate.setToolTipText("Taza de baudios por defecto para comunicación");

        lblDefaultBaudRate.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblDefaultBaudRate.setText("Baud Rate:");

        spinnerDataBits.setModel(new javax.swing.SpinnerNumberModel(8, 5, 16, 1));
        spinnerDataBits.setToolTipText("Taza de baudios por defecto para comunicación");

        lblUartParity.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblUartParity.setText("Parity:");

        lblStopBits.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblStopBits.setText("Stop bits:");

        spinnerStopBits.setToolTipText("Taza de baudios por defecto para comunicación");

        lblFlowControll1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblFlowControll1.setText("Flow Control:");

        javax.swing.GroupLayout panelGeneralUartWorkSpaceParametersLayout = new javax.swing.GroupLayout(panelGeneralUartWorkSpaceParameters);
        panelGeneralUartWorkSpaceParameters.setLayout(panelGeneralUartWorkSpaceParametersLayout);
        panelGeneralUartWorkSpaceParametersLayout.setHorizontalGroup(
            panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralUartWorkSpaceParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralUartWorkSpaceParametersLayout.createSequentialGroup()
                        .addComponent(lblUartParity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxParityMode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStopBits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerStopBits))
                    .addGroup(panelGeneralUartWorkSpaceParametersLayout.createSequentialGroup()
                        .addGroup(panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGeneralUartWorkSpaceParametersLayout.createSequentialGroup()
                                .addComponent(lblDefaultBaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerBaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataBits, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerDataBits, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGeneralUartWorkSpaceParametersLayout.createSequentialGroup()
                                .addComponent(lblFlowControll1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxFlowControlModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(209, 209, 209)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGeneralUartWorkSpaceParametersLayout.setVerticalGroup(
            panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralUartWorkSpaceParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDefaultBaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataBits, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerDataBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUartParity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxParityMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStopBits, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerStopBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFlowControlModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlowControll1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelConsoleAndSendParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Envio y consola"));

        lblEndingMode.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblEndingMode.setText("Tx Ending");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Stamp en consola"));

        configTimeStampButonGroup.add(radioButtonDisableTimeStamp);
        radioButtonDisableTimeStamp.setText("No permitir");

        configTimeStampButonGroup.add(radioButtonEnableTimeStamp);
        radioButtonEnableTimeStamp.setText("Permitir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonEnableTimeStamp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonDisableTimeStamp)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonDisableTimeStamp)
                    .addComponent(radioButtonEnableTimeStamp))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblDisplayMode.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblDisplayMode.setText("Display");

        javax.swing.GroupLayout panelConsoleAndSendParametersLayout = new javax.swing.GroupLayout(panelConsoleAndSendParameters);
        panelConsoleAndSendParameters.setLayout(panelConsoleAndSendParametersLayout);
        panelConsoleAndSendParametersLayout.setHorizontalGroup(
            panelConsoleAndSendParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsoleAndSendParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelConsoleAndSendParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndingMode)
                    .addComponent(lblDisplayMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsoleAndSendParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxTxEndingMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxConsoleDisplayMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelConsoleAndSendParametersLayout.setVerticalGroup(
            panelConsoleAndSendParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsoleAndSendParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsoleAndSendParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConsoleAndSendParametersLayout.createSequentialGroup()
                        .addGroup(panelConsoleAndSendParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEndingMode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxTxEndingMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConsoleAndSendParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisplayMode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxConsoleDisplayMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFramingModeParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Framing"));

        lblFramingMode.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblFramingMode.setText("Framing mode:");

        javax.swing.GroupLayout panelFramingModeParametersLayout = new javax.swing.GroupLayout(panelFramingModeParameters);
        panelFramingModeParameters.setLayout(panelFramingModeParametersLayout);
        panelFramingModeParametersLayout.setHorizontalGroup(
            panelFramingModeParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFramingModeParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFramingMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxFramingmode, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFramingModeParametersLayout.setVerticalGroup(
            panelFramingModeParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFramingModeParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFramingModeParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFramingMode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxFramingmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelUartSettingsLayout = new javax.swing.GroupLayout(panelUartSettings);
        panelUartSettings.setLayout(panelUartSettingsLayout);
        panelUartSettingsLayout.setHorizontalGroup(
            panelUartSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneralUartWorkSpaceParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelConsoleAndSendParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFramingModeParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUartSettingsLayout.setVerticalGroup(
            panelUartSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUartSettingsLayout.createSequentialGroup()
                .addComponent(panelGeneralUartWorkSpaceParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConsoleAndSendParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFramingModeParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        tabbPaneParametersFields.addTab("Configuración", panelUartSettings);

        buttonCreateWorkspace.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        buttonCreateWorkspace.setText("Crear");
        buttonCreateWorkspace.addActionListener(this::createWorkSpace);

        buttonCancel.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(this::onCancelButton);

        javax.swing.GroupLayout panelPrincipalContainerLayout = new javax.swing.GroupLayout(panelPrincipalContainer);
        panelPrincipalContainer.setLayout(panelPrincipalContainerLayout);
        panelPrincipalContainerLayout.setHorizontalGroup(
            panelPrincipalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbPaneParametersFields)
            .addGroup(panelPrincipalContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCreateWorkspace))
        );
        panelPrincipalContainerLayout.setVerticalGroup(
            panelPrincipalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalContainerLayout.createSequentialGroup()
                .addComponent(tabbPaneParametersFields, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateWorkspace)
                    .addComponent(buttonCancel))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setAccepted(boolean accepted){
        this.accepted = accepted;
    }
    
    public boolean isAccepted(){
        return this.accepted;
    }
    
    public WorkSpaceProperties getWorkSpaceProperties(){
        return this.initialWorkSpaceProperties;
    }
    
    private void setCurrentDateOnWorkApaceCreation() {
        LocalDate current = LocalDate.now();
        this.generalWorkspaceDataParameters.getTextFieldCreatedAt().setText(current.toString());
    }

    private void addGeneralWorkSpaceDataParameters(){
        
        this.panelWorkSpaceGeneralSettings.add(this.generalWorkspaceDataParameters,BorderLayout.CENTER);
        
    }
    
    /**
     * Generación y creación de un nuevo espacio de trabajo.
     *
     * @param evt
     */
    private void createWorkSpace(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createWorkSpace
        // TODO add your handling code here:

        try {
            
            if(!this.generalWorkspaceDataParameters.checkEmptieFieldsInWorkspaceData()){
                JOptionPane.showMessageDialog(this, "Hace falta informacion", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //Se crea el objeto del espacio de trabajo
            this.initialWorkSpaceProperties = this.mapWorkSpaceProperties();
            
            //El estado del Dialog es 'Aceptado'
            this.accepted = this.initialWorkSpaceProperties != null;
            
            //Se guarda el archivo json con los datos del espacio de trabajo
            WorkSpaceFileStorer storer = new WorkSpaceFileStorer();            
            storer.save(this.initialWorkSpaceProperties);
            
            this.dispose();
            
        } catch (IOException ioEx) {
            
            this.accepted = false;
            ioEx.printStackTrace(System.err);
            JOptionPane.showMessageDialog(this, "Error al crear espacio de trabajo: " + ioEx.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {
            
            this.accepted = false;
            ex.printStackTrace(System.err);
            JOptionPane.showMessageDialog(this, "Error al crear espacio de trabajo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            
        }

    }//GEN-LAST:event_createWorkSpace

    private void onCancelButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancelButton
        // TODO add your handling code here:
        this.accepted = false;
        this.dispose();
    }//GEN-LAST:event_onCancelButton

    private void onClosingDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onClosingDialog
        // TODO add your handling code here:
        this.accepted = this.initialWorkSpaceProperties != null;
    }//GEN-LAST:event_onClosingDialog

    private WorkSpaceProperties mapWorkSpaceProperties() {

        try {

            WorkSpaceProperties.SerialConfig serial = new WorkSpaceProperties.SerialConfig();
            serial.setBaudRate(((Number) spinnerBaudRate.getValue()).intValue());
            serial.setDataBits(((Number) spinnerDataBits.getValue()).intValue());
            serial.setStopBits(((Number) spinnerStopBits.getValue()).doubleValue());
            serial.setParityMode((ParityMode) comboBoxParityMode.getSelectedItem());
            serial.setFlowControlMode((FlowControlMode) comboBoxFlowControlModel.getSelectedItem());

            WorkSpaceProperties props = new WorkSpaceProperties().builder()
                    .setName(this.generalWorkspaceDataParameters.getTextFieldWorkSpaceName().getText().trim())
                    .setAuthor(this.generalWorkspaceDataParameters.getTextFieldAuthorsName().getText().trim())
                    .setCreatedAt(LocalDateTime.now())
                    .setPath(this.generalWorkspaceDataParameters.getTextFieldSourcePath().getText().trim())
                    .setVersion(this.generalWorkspaceDataParameters.getTextFieldWorkSpaceVersion().getText().trim())
                    .setDescription(this.generalWorkspaceDataParameters.getTextAreaDescriptionWorkspace().getText().isEmpty() ? "" : this.generalWorkspaceDataParameters.getTextAreaDescriptionWorkspace().getText())
                    .setSerial(serial)
                    .setTxtEndingMode((TxEndingMode) comboBoxTxEndingMode.getSelectedItem())
                    .setDisplayMode((ConsoleDisplayMode) comboBoxConsoleDisplayMode.getSelectedItem())
                    .setTimeStampEnabled(this.radioButtonEnableTimeStamp.isSelected())
                    .setFramingMode((FramingMode) comboBoxFramingmode.getSelectedItem())
                    .build();

            System.out.println(props.toString());

            return props;

        } catch (Exception ex) {
            ex.printStackTrace(System.err);
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

    }        

    /**
     * Set the inicial values of the combobox from <code>ParityMode</code> enum
     *
     * @author Pablo_g
     * @see ParityMode
     */
    private void configParityModeCombobox() {
        this.comboBoxParityMode.setModel(new DefaultComboBoxModel<>(ParityMode.values()));
    }

    /**
     * Set the inicial values of the combobox from <code>FlowControlMode</code>
     * enum
     *
     * @author pablo_g
     * @see FlowControlMode
     */
    private void configFlowControlModeCombobox() {
        this.comboBoxFlowControlModel.setModel(new DefaultComboBoxModel<>(FlowControlMode.values()));
    }

    private void configureTxEndingmodeComboBox() {
        this.comboBoxTxEndingMode.setModel(new DefaultComboBoxModel<>(TxEndingMode.values()));
    }

    private void configureFramingModeComboBox() {
        this.comboBoxFramingmode.setModel(new DefaultComboBoxModel<>(FramingMode.values()));
    }

    /**
     * Asigna el modelo de datos el combobox para seleccionar el modo de
     * visualización de Texto en la consola. los valores son cargados desde
     * {@code ConsoleDisplayMode}.
     *
     * @author Pablo_g
     * @see ConsoleDisplayMode
     */
    private void configureConsoleDisplayModeComboBox() {
        this.comboBoxConsoleDisplayMode.setModel(new DefaultComboBoxModel<>(ConsoleDisplayMode.values()));
    }

    /**
     * Set the permitted values for the JSpinner used to set the Stop bits mode
     *
     * @author Pablo_g
     */
    private void configureStopbitsSpinnerModel() {
        SpinnerNumberModel model = new SpinnerNumberModel(1d, 1d, 2d, 0.5d);
        this.spinnerStopBits.setModel(model);

        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(this.spinnerStopBits, "#0.#");
        this.spinnerStopBits.setEditor(editor);

        DecimalFormat format = editor.getFormat();
        format.setMinimumFractionDigits(0);
        format.setMaximumFractionDigits(1);
        editor.getTextField().setHorizontalAlignment(SwingConstants.CENTER);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreateWorkspace;
    private javax.swing.JComboBox<ConsoleDisplayMode> comboBoxConsoleDisplayMode;
    private javax.swing.JComboBox<FlowControlMode> comboBoxFlowControlModel;
    private javax.swing.JComboBox<FramingMode> comboBoxFramingmode;
    private javax.swing.JComboBox<ParityMode> comboBoxParityMode;
    private javax.swing.JComboBox<TxEndingMode> comboBoxTxEndingMode;
    private javax.swing.ButtonGroup configTimeStampButonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataBits;
    private javax.swing.JLabel lblDefaultBaudRate;
    private javax.swing.JLabel lblDisplayMode;
    private javax.swing.JLabel lblEndingMode;
    private javax.swing.JLabel lblFlowControll1;
    private javax.swing.JLabel lblFramingMode;
    private javax.swing.JLabel lblStopBits;
    private javax.swing.JLabel lblUartParity;
    private javax.swing.JPanel panelConsoleAndSendParameters;
    private javax.swing.JPanel panelFramingModeParameters;
    private javax.swing.JPanel panelGeneralUartWorkSpaceParameters;
    private javax.swing.JPanel panelPrincipalContainer;
    private javax.swing.JPanel panelUartSettings;
    private javax.swing.JPanel panelWorkSpaceGeneralSettings;
    private javax.swing.JRadioButton radioButtonDisableTimeStamp;
    private javax.swing.JRadioButton radioButtonEnableTimeStamp;
    private javax.swing.JSpinner spinnerBaudRate;
    private javax.swing.JSpinner spinnerDataBits;
    private javax.swing.JSpinner spinnerStopBits;
    private javax.swing.JTabbedPane tabbPaneParametersFields;
    // End of variables declaration//GEN-END:variables
}
