/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tectuinno.seriallab.view;

/**
 *
 * @author root
 */
public class FrWorkSpaceWizard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrWorkSpaceWizard.class.getName());

    /**
     * Creates new form FrWorkSpaceWizard
     */
    public FrWorkSpaceWizard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelPrincipalContainer = new javax.swing.JPanel();
        tabbPaneParametersFields = new javax.swing.JTabbedPane();
        panelWorkSpaceGeneralSettings = new javax.swing.JPanel();
        panelGeneralWorkspaceDataParameters = new javax.swing.JPanel();
        lblWorkspaceName = new javax.swing.JLabel();
        lblAuthorsName = new javax.swing.JLabel();
        textFieldWorkSpaceName = new javax.swing.JTextField();
        textFieldAuthorsName = new javax.swing.JTextField();
        lblCreatedAt = new javax.swing.JLabel();
        textFieldCreatedAt = new javax.swing.JTextField();
        lblWorkspaceVersion = new javax.swing.JLabel();
        textFieldSourcePath = new javax.swing.JTextField();
        btnOpenFileChoser = new javax.swing.JButton();
        lblSourcePath1 = new javax.swing.JLabel();
        textFieldWorkSpaceVersion = new javax.swing.JTextField();
        panelUartSettings = new javax.swing.JPanel();
        panelGeneralUartWorkSpaceParameters = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear nuevo espacio de trabajo");

        panelGeneralWorkspaceDataParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Generales"));

        lblWorkspaceName.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblWorkspaceName.setText("Nombre:");

        lblAuthorsName.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblAuthorsName.setText("Autor");

        textFieldWorkSpaceName.setToolTipText("Nombre que se le asigna al espacio de trabajo");

        textFieldAuthorsName.setToolTipText("Autor que crea este espacio de trabajo");

        lblCreatedAt.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblCreatedAt.setText("Fecha de creación:");

        textFieldCreatedAt.setEditable(false);
        textFieldCreatedAt.setToolTipText("Fecha actual en la que se está creando el nuevo espacio de trabajo");

        lblWorkspaceVersion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblWorkspaceVersion.setText("Version");

        textFieldSourcePath.setEditable(false);
        textFieldSourcePath.setToolTipText("Ruta en la cual serán almacenados los datos del espacio de trabajo");

        btnOpenFileChoser.setText("src...");
        btnOpenFileChoser.setToolTipText("Abrir el explorador de archivos");
        btnOpenFileChoser.addActionListener(this::btnOpenFileChoserActionPerformed);

        lblSourcePath1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblSourcePath1.setText("Carpeta raiz");

        javax.swing.GroupLayout panelGeneralWorkspaceDataParametersLayout = new javax.swing.GroupLayout(panelGeneralWorkspaceDataParameters);
        panelGeneralWorkspaceDataParameters.setLayout(panelGeneralWorkspaceDataParametersLayout);
        panelGeneralWorkspaceDataParametersLayout.setHorizontalGroup(
            panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblWorkspaceName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldWorkSpaceName))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblAuthorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldAuthorsName))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldCreatedAt))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblSourcePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldSourcePath, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenFileChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 69, Short.MAX_VALUE))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblWorkspaceVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldWorkSpaceVersion)))
                .addContainerGap())
        );
        panelGeneralWorkspaceDataParametersLayout.setVerticalGroup(
            panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkspaceName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldWorkSpaceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAuthorsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldSourcePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSourcePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOpenFileChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkspaceVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldWorkSpaceVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelWorkSpaceGeneralSettingsLayout = new javax.swing.GroupLayout(panelWorkSpaceGeneralSettings);
        panelWorkSpaceGeneralSettings.setLayout(panelWorkSpaceGeneralSettingsLayout);
        panelWorkSpaceGeneralSettingsLayout.setHorizontalGroup(
            panelWorkSpaceGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneralWorkspaceDataParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelWorkSpaceGeneralSettingsLayout.setVerticalGroup(
            panelWorkSpaceGeneralSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWorkSpaceGeneralSettingsLayout.createSequentialGroup()
                .addComponent(panelGeneralWorkspaceDataParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 224, Short.MAX_VALUE))
        );

        tabbPaneParametersFields.addTab("General", panelWorkSpaceGeneralSettings);

        panelGeneralUartWorkSpaceParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros UART"));

        javax.swing.GroupLayout panelGeneralUartWorkSpaceParametersLayout = new javax.swing.GroupLayout(panelGeneralUartWorkSpaceParameters);
        panelGeneralUartWorkSpaceParameters.setLayout(panelGeneralUartWorkSpaceParametersLayout);
        panelGeneralUartWorkSpaceParametersLayout.setHorizontalGroup(
            panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        panelGeneralUartWorkSpaceParametersLayout.setVerticalGroup(
            panelGeneralUartWorkSpaceParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelUartSettingsLayout = new javax.swing.GroupLayout(panelUartSettings);
        panelUartSettings.setLayout(panelUartSettingsLayout);
        panelUartSettingsLayout.setHorizontalGroup(
            panelUartSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneralUartWorkSpaceParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUartSettingsLayout.setVerticalGroup(
            panelUartSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUartSettingsLayout.createSequentialGroup()
                .addComponent(panelGeneralUartWorkSpaceParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );

        tabbPaneParametersFields.addTab("UART", panelUartSettings);

        javax.swing.GroupLayout panelPrincipalContainerLayout = new javax.swing.GroupLayout(panelPrincipalContainer);
        panelPrincipalContainer.setLayout(panelPrincipalContainerLayout);
        panelPrincipalContainerLayout.setHorizontalGroup(
            panelPrincipalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbPaneParametersFields)
        );
        panelPrincipalContainerLayout.setVerticalGroup(
            panelPrincipalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbPaneParametersFields)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenFileChoserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileChoserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenFileChoserActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenFileChoser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAuthorsName;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblSourcePath1;
    private javax.swing.JLabel lblWorkspaceName;
    private javax.swing.JLabel lblWorkspaceVersion;
    private javax.swing.JPanel panelGeneralUartWorkSpaceParameters;
    private javax.swing.JPanel panelGeneralWorkspaceDataParameters;
    private javax.swing.JPanel panelPrincipalContainer;
    private javax.swing.JPanel panelUartSettings;
    private javax.swing.JPanel panelWorkSpaceGeneralSettings;
    private javax.swing.JTabbedPane tabbPaneParametersFields;
    private javax.swing.JTextField textFieldAuthorsName;
    private javax.swing.JTextField textFieldCreatedAt;
    private javax.swing.JTextField textFieldSourcePath;
    private javax.swing.JTextField textFieldWorkSpaceName;
    private javax.swing.JTextField textFieldWorkSpaceVersion;
    // End of variables declaration//GEN-END:variables
}
