/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tectuinno.seriallab.view;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * Formulario principal
 * @author root
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalContainer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuFileNew = new javax.swing.JMenu();
        jMenuItemNewWorkSpace = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tectuinno Serial Lab");

        javax.swing.GroupLayout panelPrincipalContainerLayout = new javax.swing.GroupLayout(panelPrincipalContainer);
        panelPrincipalContainer.setLayout(panelPrincipalContainerLayout);
        panelPrincipalContainerLayout.setHorizontalGroup(
            panelPrincipalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelPrincipalContainerLayout.setVerticalGroup(
            panelPrincipalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jMenuFile.setText("Archivo");

        jMenuFileNew.setText("Nuevo");

        jMenuItemNewWorkSpace.setText("Espacio de trabajo");
        jMenuItemNewWorkSpace.addActionListener(this::openWorkSpaceWizard);
        jMenuFileNew.add(jMenuItemNewWorkSpace);

        jMenuFile.add(jMenuFileNew);

        jMenuBar1.add(jMenuFile);

        jMenu2.setText("Propiedades");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * this method call a new instance of a {@code FrWorkSpaceWizard}
     * @param evt 
     */
    private void openWorkSpaceWizard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openWorkSpaceWizard
        
        JFrame parent = this;
        
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run(){
                try{
                    
                    FrWorkSpaceWizard frameWizar = new FrWorkSpaceWizard();
                    frameWizar.setLocationRelativeTo(parent);
                    frameWizar.setVisible(true);
                    frameWizar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    
                }catch(Exception ex){
                    System.out.println("Error: " + ex.getMessage());
                    ex.printStackTrace(System.err);
                }
            }
        });
        
    }//GEN-LAST:event_openWorkSpaceWizard
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuFileNew;
    private javax.swing.JMenuItem jMenuItemNewWorkSpace;
    private javax.swing.JPanel panelPrincipalContainer;
    // End of variables declaration//GEN-END:variables
}
