/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tectuinno.seriallab.view.uart_com.components;

/**
 *
 * @author root
 */
public class PanelConsolLogResult extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsolLogResult
     */
    public PanelConsolLogResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsoleHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonSaveCurrentLogs = new javax.swing.JButton();
        buttonDeleteAllLogs = new javax.swing.JButton();
        jScrollPaneTextAreaContainer = new javax.swing.JScrollPane();
        textAreaLogsContainer = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel1.setText("Bitácora de eventos");

        buttonSaveCurrentLogs.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        buttonSaveCurrentLogs.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        buttonSaveCurrentLogs.setText("Guardar");

        buttonDeleteAllLogs.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        buttonDeleteAllLogs.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        buttonDeleteAllLogs.setText("Limpiar");

        javax.swing.GroupLayout panelConsoleHeaderLayout = new javax.swing.GroupLayout(panelConsoleHeader);
        panelConsoleHeader.setLayout(panelConsoleHeaderLayout);
        panelConsoleHeaderLayout.setHorizontalGroup(
            panelConsoleHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsoleHeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonDeleteAllLogs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSaveCurrentLogs))
        );
        panelConsoleHeaderLayout.setVerticalGroup(
            panelConsoleHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(panelConsoleHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(buttonSaveCurrentLogs)
                .addComponent(buttonDeleteAllLogs))
        );

        jScrollPaneTextAreaContainer.setViewportView(textAreaLogsContainer);

        textAreaLogsContainer.setColumns(20);
        textAreaLogsContainer.setRows(5);
        jScrollPaneTextAreaContainer.setViewportView(textAreaLogsContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsoleHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneTextAreaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConsoleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTextAreaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteAllLogs;
    private javax.swing.JButton buttonSaveCurrentLogs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneTextAreaContainer;
    private javax.swing.JPanel panelConsoleHeader;
    private javax.swing.JTextArea textAreaLogsContainer;
    // End of variables declaration//GEN-END:variables
}
