/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tectuinno.seriallab.view.uart_com.components;

/**
 *
 * @author root
 */
public class PanelConsolLogResult extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsolLogResult
     */
    public PanelConsolLogResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsoleHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonSaveCurrentLogs = new javax.swing.JButton();
        buttonDeleteAllLogs = new javax.swing.JButton();
        jScrollPaneTextAreaContainer = new javax.swing.JScrollPane();
        TextAreaLogsContainer = new javax.swing.JTextArea();

        jLabel1.setText("Terminal de depuración y logs");

        buttonSaveCurrentLogs.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        buttonSaveCurrentLogs.setText("Guardar");

        buttonDeleteAllLogs.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        buttonDeleteAllLogs.setText("Limpiar");

        javax.swing.GroupLayout panelConsoleHeaderLayout = new javax.swing.GroupLayout(panelConsoleHeader);
        panelConsoleHeader.setLayout(panelConsoleHeaderLayout);
        panelConsoleHeaderLayout.setHorizontalGroup(
            panelConsoleHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsoleHeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(buttonDeleteAllLogs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSaveCurrentLogs))
        );
        panelConsoleHeaderLayout.setVerticalGroup(
            panelConsoleHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsoleHeaderLayout.createSequentialGroup()
                .addGroup(panelConsoleHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buttonSaveCurrentLogs)
                    .addComponent(buttonDeleteAllLogs))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jScrollPaneTextAreaContainer.setViewportView(TextAreaLogsContainer);

        TextAreaLogsContainer.setEditable(false);
        TextAreaLogsContainer.setBackground(new java.awt.Color(51, 51, 51));
        TextAreaLogsContainer.setColumns(20);
        TextAreaLogsContainer.setFont(new java.awt.Font("Liberation Mono", 0, 12)); // NOI18N
        TextAreaLogsContainer.setForeground(new java.awt.Color(95, 201, 63));
        TextAreaLogsContainer.setRows(5);
        TextAreaLogsContainer.setText("_______________________\nTectuinno Serial\n------------------------------------");
        jScrollPaneTextAreaContainer.setViewportView(TextAreaLogsContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsoleHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneTextAreaContainer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConsoleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTextAreaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaLogsContainer;
    private javax.swing.JButton buttonDeleteAllLogs;
    private javax.swing.JButton buttonSaveCurrentLogs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneTextAreaContainer;
    private javax.swing.JPanel panelConsoleHeader;
    // End of variables declaration//GEN-END:variables
}
