/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tectuinno.seriallab.view.uart_com.components;

/**
 *
 * @author root
 */
public class PanelSerialCommunication extends javax.swing.JPanel {

    /**
     * Creates new form PanelSerialCommunication
     */
    public PanelSerialCommunication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txSendModeButtonGroup = new javax.swing.ButtonGroup();
        configTimeStampButtonGroup = new javax.swing.ButtonGroup();
        panelSendingConfigParametersContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        radioButtonAsciiMode = new javax.swing.JRadioButton();
        radioButtonAsciiMode1 = new javax.swing.JRadioButton();
        radioButtonAsciiMode2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tx Mod", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 10))); // NOI18N

        radioButtonAsciiMode.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonAsciiMode.setText("ASCII");

        radioButtonAsciiMode1.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonAsciiMode1.setText("Hex");

        radioButtonAsciiMode2.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonAsciiMode2.setText("Ambos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radioButtonAsciiMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonAsciiMode1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonAsciiMode2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioButtonAsciiMode)
                .addComponent(radioButtonAsciiMode1)
                .addComponent(radioButtonAsciiMode2))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Stamp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 10))); // NOI18N

        jRadioButton1.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        jRadioButton1.setText("On");

        jRadioButton2.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        jRadioButton2.setText("Off");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2))
        );

        javax.swing.GroupLayout panelSendingConfigParametersContainerLayout = new javax.swing.GroupLayout(panelSendingConfigParametersContainer);
        panelSendingConfigParametersContainer.setLayout(panelSendingConfigParametersContainerLayout);
        panelSendingConfigParametersContainerLayout.setHorizontalGroup(
            panelSendingConfigParametersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSendingConfigParametersContainerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 265, Short.MAX_VALUE))
        );
        panelSendingConfigParametersContainerLayout.setVerticalGroup(
            panelSendingConfigParametersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSendingConfigParametersContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSendingConfigParametersContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 361, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup configTimeStampButtonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel panelSendingConfigParametersContainer;
    private javax.swing.JRadioButton radioButtonAsciiMode;
    private javax.swing.JRadioButton radioButtonAsciiMode1;
    private javax.swing.JRadioButton radioButtonAsciiMode2;
    private javax.swing.ButtonGroup txSendModeButtonGroup;
    // End of variables declaration//GEN-END:variables
}
