/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tectuinno.seriallab.view.uart_com.components;

import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author root
 */
public class PanelSerialCommunication extends javax.swing.JPanel {

    /**
     * Creates new form PanelSerialCommunication
     */
    public PanelSerialCommunication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txSendModeButtonGroup = new javax.swing.ButtonGroup();
        configTimeStampButtonGroup = new javax.swing.ButtonGroup();
        panelSendingConfigParametersContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        radioButtonAsciiMode = new javax.swing.JRadioButton();
        radioButtonHexMode = new javax.swing.JRadioButton();
        radioButtonBothMode = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        radioButtonTimeStampOn = new javax.swing.JRadioButton();
        radioButtonTimeStampOff = new javax.swing.JRadioButton();
        buttonCleanAllMessages = new javax.swing.JButton();
        splitPaneChatContainer = new javax.swing.JSplitPane();
        panelAllMessagesContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPaneAllMessages = new javax.swing.JTextPane();
        panelWrittingZoneContainer = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaMessageToSend = new javax.swing.JTextArea();
        buttonSendMessage = new javax.swing.JButton();
        lblForTextFieldFinalCharacter = new javax.swing.JLabel();
        textFieldFinalCharacterLine = new javax.swing.JTextField();
        lblForSpinnerTiming = new javax.swing.JLabel();
        jSpinnerTimingSend = new javax.swing.JSpinner();
        toggleEnableTimingSending = new javax.swing.JToggleButton();

        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tx Mod", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 10))); // NOI18N

        txSendModeButtonGroup.add(radioButtonAsciiMode);
        radioButtonAsciiMode.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonAsciiMode.setText("ASCII");

        txSendModeButtonGroup.add(radioButtonHexMode);
        radioButtonHexMode.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonHexMode.setText("Hex");

        txSendModeButtonGroup.add(radioButtonBothMode);
        radioButtonBothMode.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonBothMode.setText("Ambos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radioButtonAsciiMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonHexMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonBothMode))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioButtonAsciiMode)
                .addComponent(radioButtonHexMode)
                .addComponent(radioButtonBothMode))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Stamp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 10))); // NOI18N

        configTimeStampButtonGroup.add(radioButtonTimeStampOn);
        radioButtonTimeStampOn.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonTimeStampOn.setText("On");

        configTimeStampButtonGroup.add(radioButtonTimeStampOff);
        radioButtonTimeStampOff.setFont(new java.awt.Font("Liberation Sans", 0, 8)); // NOI18N
        radioButtonTimeStampOff.setText("Off");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(radioButtonTimeStampOn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonTimeStampOff))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioButtonTimeStampOn)
                .addComponent(radioButtonTimeStampOff))
        );

        buttonCleanAllMessages.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        buttonCleanAllMessages.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        buttonCleanAllMessages.setText("Limpiar");

        javax.swing.GroupLayout panelSendingConfigParametersContainerLayout = new javax.swing.GroupLayout(panelSendingConfigParametersContainer);
        panelSendingConfigParametersContainer.setLayout(panelSendingConfigParametersContainerLayout);
        panelSendingConfigParametersContainerLayout.setHorizontalGroup(
            panelSendingConfigParametersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSendingConfigParametersContainerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCleanAllMessages)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSendingConfigParametersContainerLayout.setVerticalGroup(
            panelSendingConfigParametersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSendingConfigParametersContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCleanAllMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        splitPaneChatContainer.setDividerLocation(290);
        splitPaneChatContainer.setDividerSize(10);
        splitPaneChatContainer.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPaneChatContainer.setLastDividerLocation(290);
        splitPaneChatContainer.setName(""); // NOI18N

        jScrollPane2.setViewportView(textPaneAllMessages);

        javax.swing.GroupLayout panelAllMessagesContainerLayout = new javax.swing.GroupLayout(panelAllMessagesContainer);
        panelAllMessagesContainer.setLayout(panelAllMessagesContainerLayout);
        panelAllMessagesContainerLayout.setHorizontalGroup(
            panelAllMessagesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        panelAllMessagesContainerLayout.setVerticalGroup(
            panelAllMessagesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        splitPaneChatContainer.setTopComponent(panelAllMessagesContainer);

        textAreaMessageToSend.setColumns(20);
        textAreaMessageToSend.setRows(5);
        jScrollPane3.setViewportView(textAreaMessageToSend);

        buttonSendMessage.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        buttonSendMessage.setText("Enviar");

        lblForTextFieldFinalCharacter.setText("Caracter Final");

        lblForSpinnerTiming.setText("intervalo");

        toggleEnableTimingSending.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        toggleEnableTimingSending.setText("Activar");

        javax.swing.GroupLayout panelWrittingZoneContainerLayout = new javax.swing.GroupLayout(panelWrittingZoneContainer);
        panelWrittingZoneContainer.setLayout(panelWrittingZoneContainerLayout);
        panelWrittingZoneContainerLayout.setHorizontalGroup(
            panelWrittingZoneContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWrittingZoneContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelWrittingZoneContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWrittingZoneContainerLayout.createSequentialGroup()
                        .addComponent(lblForTextFieldFinalCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldFinalCharacterLine, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(panelWrittingZoneContainerLayout.createSequentialGroup()
                        .addComponent(lblForSpinnerTiming)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTimingSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleEnableTimingSending, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(buttonSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelWrittingZoneContainerLayout.setVerticalGroup(
            panelWrittingZoneContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWrittingZoneContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWrittingZoneContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForTextFieldFinalCharacter)
                    .addComponent(textFieldFinalCharacterLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelWrittingZoneContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForSpinnerTiming)
                    .addComponent(jSpinnerTimingSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleEnableTimingSending))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        splitPaneChatContainer.setRightComponent(panelWrittingZoneContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSendingConfigParametersContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(splitPaneChatContainer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSendingConfigParametersContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPaneChatContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        
        this.splitPaneChatContainer.setDividerLocation(290 - this.getHeight());
        
    }//GEN-LAST:event_formAncestorResized

    /**
     * Se expone el contenedor actual del area de mensajes para manipular sus propiedades
     * desde el contenedor padre
     * @return 
     */
    public JSplitPane getSplitPaneChatContainer(){
        return this.splitPaneChatContainer;
    }

    public JSpinner getjSpinnerTimingSend() {
        return jSpinnerTimingSend;
    }

    public JRadioButton getRadioButtonAsciiMode() {
        return radioButtonAsciiMode;
    }

    public JRadioButton getRadioButtonBothMode() {
        return radioButtonBothMode;
    }

    public JRadioButton getRadioButtonHexMode() {
        return radioButtonHexMode;
    }

    public JRadioButton getRadioButtonTimeStampOff() {
        return radioButtonTimeStampOff;
    }

    public JRadioButton getRadioButtonTimeStampOn() {
        return radioButtonTimeStampOn;
    }

    public JTextArea getTextAreaMessageToSend() {
        return textAreaMessageToSend;
    }

    public JTextField getTextFieldFinalCharacterLine() {
        return textFieldFinalCharacterLine;
    }

    public JTextPane getTextPaneAllMessages() {
        return textPaneAllMessages;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCleanAllMessages;
    private javax.swing.JButton buttonSendMessage;
    private javax.swing.ButtonGroup configTimeStampButtonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerTimingSend;
    private javax.swing.JLabel lblForSpinnerTiming;
    private javax.swing.JLabel lblForTextFieldFinalCharacter;
    private javax.swing.JPanel panelAllMessagesContainer;
    private javax.swing.JPanel panelSendingConfigParametersContainer;
    private javax.swing.JPanel panelWrittingZoneContainer;
    private javax.swing.JRadioButton radioButtonAsciiMode;
    private javax.swing.JRadioButton radioButtonBothMode;
    private javax.swing.JRadioButton radioButtonHexMode;
    private javax.swing.JRadioButton radioButtonTimeStampOff;
    private javax.swing.JRadioButton radioButtonTimeStampOn;
    private javax.swing.JSplitPane splitPaneChatContainer;
    private javax.swing.JTextArea textAreaMessageToSend;
    private javax.swing.JTextField textFieldFinalCharacterLine;
    private javax.swing.JTextPane textPaneAllMessages;
    private javax.swing.JToggleButton toggleEnableTimingSending;
    private javax.swing.ButtonGroup txSendModeButtonGroup;
    // End of variables declaration//GEN-END:variables
}
