/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tectuinno.seriallab.view.shared.work_space;

import java.awt.Color;
import java.awt.Component;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author pablo-g
 */
public class GeneralWorkspaceDataParameters extends javax.swing.JPanel {

    /**
     * Creates new form GeneralWorkspaceDataParameters
     */
    public GeneralWorkspaceDataParameters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneralWorkspaceDataParameters = new javax.swing.JPanel();
        lblWorkspaceName = new javax.swing.JLabel();
        lblAuthorsName = new javax.swing.JLabel();
        textFieldWorkSpaceName = new javax.swing.JTextField();
        textFieldAuthorsName = new javax.swing.JTextField();
        lblCreatedAt = new javax.swing.JLabel();
        textFieldCreatedAt = new javax.swing.JTextField();
        lblWorkspaceVersion = new javax.swing.JLabel();
        textFieldSourcePath = new javax.swing.JTextField();
        btnOpenFileChoser = new javax.swing.JButton();
        lblSourcePath1 = new javax.swing.JLabel();
        textFieldWorkSpaceVersion = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescriptionWorkspace = new javax.swing.JTextArea();

        panelGeneralWorkspaceDataParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Generales"));

        lblWorkspaceName.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblWorkspaceName.setText("Nombre:");

        lblAuthorsName.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblAuthorsName.setText("Autor");

        textFieldWorkSpaceName.setToolTipText("Nombre que se le asigna al espacio de trabajo");
        textFieldWorkSpaceName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldWorkSpaceNameverifyNameWasWritten(evt);
            }
        });

        textFieldAuthorsName.setToolTipText("Autor que crea este espacio de trabajo");
        textFieldAuthorsName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldAuthorsNameverifyAuthorsName(evt);
            }
        });

        lblCreatedAt.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblCreatedAt.setText("Fecha de creación:");

        textFieldCreatedAt.setEditable(false);
        textFieldCreatedAt.setToolTipText("Fecha actual en la que se está creando el nuevo espacio de trabajo");

        lblWorkspaceVersion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblWorkspaceVersion.setText("Version");

        textFieldSourcePath.setEditable(false);
        textFieldSourcePath.setToolTipText("Ruta en la cual serán almacenados los datos del espacio de trabajo");
        textFieldSourcePath.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldSourcePathverifyAsignedRootPath(evt);
            }
        });

        btnOpenFileChoser.setText("src...");
        btnOpenFileChoser.setToolTipText("Abrir el explorador de archivos");
        btnOpenFileChoser.addActionListener(this::btnOpenFileChoserchooseRootPathWorkspace);

        lblSourcePath1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblSourcePath1.setText("Carpeta raiz");

        textFieldWorkSpaceVersion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldWorkSpaceVersionverifyVersionWritten(evt);
            }
        });

        lblDescripcion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblDescripcion.setText("Descripción");

        textAreaDescriptionWorkspace.setColumns(20);
        textAreaDescriptionWorkspace.setRows(5);
        jScrollPane1.setViewportView(textAreaDescriptionWorkspace);

        javax.swing.GroupLayout panelGeneralWorkspaceDataParametersLayout = new javax.swing.GroupLayout(panelGeneralWorkspaceDataParameters);
        panelGeneralWorkspaceDataParameters.setLayout(panelGeneralWorkspaceDataParametersLayout);
        panelGeneralWorkspaceDataParametersLayout.setHorizontalGroup(
            panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblWorkspaceName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldWorkSpaceName))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblAuthorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldAuthorsName))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldCreatedAt))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblSourcePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldSourcePath, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenFileChoser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblWorkspaceVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldWorkSpaceVersion))
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelGeneralWorkspaceDataParametersLayout.setVerticalGroup(
            panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralWorkspaceDataParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkspaceName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldWorkSpaceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAuthorsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldSourcePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSourcePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOpenFileChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralWorkspaceDataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkspaceVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldWorkSpaceVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneralWorkspaceDataParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneralWorkspaceDataParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldWorkSpaceNameverifyNameWasWritten(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldWorkSpaceNameverifyNameWasWritten
        this.colorizeBorderOfEmptyFieldsOnFocuslost(this.textFieldWorkSpaceName);
        this.checkEmptieFieldsInWorkspaceData();
    }//GEN-LAST:event_textFieldWorkSpaceNameverifyNameWasWritten

    private void textFieldAuthorsNameverifyAuthorsName(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldAuthorsNameverifyAuthorsName
        // TODO add your handling code here:
        this.colorizeBorderOfEmptyFieldsOnFocuslost(this.textFieldAuthorsName);
        this.checkEmptieFieldsInWorkspaceData();
    }//GEN-LAST:event_textFieldAuthorsNameverifyAuthorsName

    private void textFieldSourcePathverifyAsignedRootPath(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldSourcePathverifyAsignedRootPath
        // TODO add your handling code here:
        this.colorizeBorderOfEmptyFieldsOnFocuslost(this.textFieldSourcePath);
        this.checkEmptieFieldsInWorkspaceData();
    }//GEN-LAST:event_textFieldSourcePathverifyAsignedRootPath

    private void btnOpenFileChoserchooseRootPathWorkspace(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileChoserchooseRootPathWorkspace

        final JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        final int returnVal = fileChooser.showDialog(this, "Seleccionar");

        if (returnVal != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "Es necesario señalar un directoio para el espacio de trabajo", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        File file = fileChooser.getSelectedFile();
        this.textFieldSourcePath.setText(file.getAbsolutePath());
    }//GEN-LAST:event_btnOpenFileChoserchooseRootPathWorkspace

    private void textFieldWorkSpaceVersionverifyVersionWritten(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldWorkSpaceVersionverifyVersionWritten
        // TODO add your handling code here:
        this.colorizeBorderOfEmptyFieldsOnFocuslost(this.textFieldWorkSpaceVersion);
        this.checkEmptieFieldsInWorkspaceData();
    }//GEN-LAST:event_textFieldWorkSpaceVersionverifyVersionWritten

    public JTextArea getTextAreaDescriptionWorkspace() {
        return textAreaDescriptionWorkspace;
    }

    public JTextField getTextFieldAuthorsName() {
        return textFieldAuthorsName;
    }

    public JTextField getTextFieldCreatedAt() {
        return textFieldCreatedAt;
    }

    public JTextField getTextFieldSourcePath() {
        return textFieldSourcePath;
    }

    public JTextField getTextFieldWorkSpaceName() {
        return textFieldWorkSpaceName;
    }

    public JTextField getTextFieldWorkSpaceVersion() {
        return textFieldWorkSpaceVersion;
    }
        
    
    
    /**
     * verifica cuales son los campos vacios en la pestaña de datos del wizar al
     * crear un workspace. si durante la verificación se encuentran campos
     * vacios el botón para crear un nuevo worksapce permanecerá desactivado.
     */
    public boolean checkEmptieFieldsInWorkspaceData() {

        boolean enableCreateButton = false;

        Component[] cmps = this.panelGeneralWorkspaceDataParameters.getComponents();

        for (Component cmp : cmps) {

            if (cmp instanceof JTextField) {
                return ((JTextField) cmp).getText().length() > 0;
            }

        }

        return false;

    }
    
    /**
     * <summary>Función únicamente visual</summary>
     * <p>
     * usado para cambiar el color de borde del @{@code JTextField} pasado como
     * parámetro.</p>
     * <ul>
     * <li>Verde: en caso de que el campo tenga datos corrector</li>
     * <li>Rojo: en caso de que el campo se encuentre vacio</li>
     * </ul>
     *
     * @param textField
     */
    private void colorizeBorderOfEmptyFieldsOnFocuslost(JTextField textField) {

        Border border = null;
        boolean dataAsigned = textField.getText().isEmpty() || textField.getText().length() <= 0;

        if (dataAsigned) {
            border = BorderFactory.createLineBorder(Color.RED);
            textField.setBorder(border);
            return;
        }

        border = BorderFactory.createLineBorder(Color.GREEN);
        textField.setBorder(border);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenFileChoser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthorsName;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblSourcePath1;
    private javax.swing.JLabel lblWorkspaceName;
    private javax.swing.JLabel lblWorkspaceVersion;
    private javax.swing.JPanel panelGeneralWorkspaceDataParameters;
    private javax.swing.JTextArea textAreaDescriptionWorkspace;
    private javax.swing.JTextField textFieldAuthorsName;
    private javax.swing.JTextField textFieldCreatedAt;
    private javax.swing.JTextField textFieldSourcePath;
    private javax.swing.JTextField textFieldWorkSpaceName;
    private javax.swing.JTextField textFieldWorkSpaceVersion;
    // End of variables declaration//GEN-END:variables
}
